name: Create Changes ZIP on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy README from docs folder
        run: cp _docs/README.pdf UK/README.pdf

      - name: Get release tag
        run: echo ::set-env name=RELEASE_TAG::${GITHUB_REF#refs/tags/}

      - name: Create changes only zip
        run: |
          git diff --diff-filter=d --name-only -z $(git rev-list -n 1 $RELEASE_TAG)^ | grep -z -v '\.prf$' | xargs -0 git archive -o changes_only_${RELEASE_TAG}.zip HEAD --
          git diff --name-only $(git rev-list -n 1 $RELEASE_TAG)^ $RELEASE_TAG -- '*.prf' | while read -r file; do
              if ! git diff "$file" | grep -q -E "^\-Settings\s+sector" && git diff "$file" | grep -q -E "^\+Settings\s+sector"; then
                  echo "$file" >> included_files.txt
              fi
          done
          zip -r changes_only_${RELEASE_TAG}.zip $(cat included_files.txt)
          rm included_files.txt

      - name: Upload changes only zip
        uses: actions/upload-artifact@v2
        with:
          name: changes_only_${RELEASE_TAG}.zip
          path: changes_only_${RELEASE_TAG}.zip
