name: Changes Only on Release
on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Copy README.pdf from docs folder
                run: cp docs/README.pdf UK/README.pdf

            - name: Get last release tag
                id: last_release
                run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

            - name: Get current release tag
                id: current_release
                run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

            - name: Create changes only zip
                run: |
                    git diff --name-only --diff-filter=ACMRT $(echo "${{ steps.last_release.outputs.tag }}") $(echo "${{ steps.current_release.outputs.tag }}") | grep -v ".prf$" > changed_files.txt
                    zip -r "changes_only_$(echo "${{ steps.current_release.outputs.tag }}").zip" -@ < changed_files.txt README.pdf

            - name: Upload changes only zip as release asset
                uses: actions/upload-release-asset@v1
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: ./changes_only_$(echo "${{ steps.current_release.outputs.tag }}").zip
                    asset_name: changes_only_$(echo "${{ steps.current_release.outputs.tag }}").zip
                    asset_content_type: application/zip
